name: Windows Build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v3

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}\build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}\build
      run: cmake  ..
    
    - name: Build
      # Build your program with the given configuration
      run: cmake --build .
      
    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
          name: latest
          path: ${{runner.workspace}}\build\Debug\atsp_taxi.exe
      
